[package]
name = "ostree-coswid-generator"
version = "0.1.0"
authors = ["Patrick Uiterwijk <patrick@puiterwijk.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
coswid = "0.1.1"
ostree = "0.9.1"

gio = "0.9.0"
